application: personalizednewscategories
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: handlers.app

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.1.1"
